<?xml version="1.0"?>
<Procedure Version="5" type="197C4F52">
    <Inputs>
        <Input id="1" type="Frame" name="In" description=""/>
        <Input id="3" type="Float" name="West" description=""/>
        <Input id="2" type="Float" name="East" description=""/>
        <Input id="5" type="Float" name="South" description=""/>
        <Input id="4" type="Float" name="North" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-4" type="Integer">0</Constant>
        <Constant id="-5" type="Bool">True</Constant>
        <Constant id="-6" type="Float">0.000000</Constant>
        <Constant id="-8" type="Integer">0</Constant>
        <Constant id="-9" type="Integer">0</Constant>
        <Constant id="-10" type="Bool">False</Constant>
        <Constant id="-11" type="Float">0.000000</Constant>
        <Constant id="-12" type="Integer">0</Constant>
        <Constant id="-13" type="Integer">1</Constant>
        <Constant id="-14" type="Bool">True</Constant>
        <Constant id="-15" type="Float">0.000000</Constant>
        <Constant id="-16" type="Integer">0</Constant>
        <Constant id="-17" type="Integer">1</Constant>
        <Constant id="-18" type="Bool">False</Constant>
        <Constant id="-19" type="Float">0.000000</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="D729EF5D">
            <Connect in="100" input="1"/>
            <Connect in="101" to="2" out="100"/>
            <Connect in="102" constant="-3"/>
            <Connect in="103" constant="-4"/>
            <Connect in="104" constant="-5"/>
        </Operator>
        <Operator id="2" type="A2AAB92C">
            <Connect in="100" constant="-6"/>
            <Connect in="101" input="2"/>
        </Operator>
        <Operator id="3" type="D729EF5D">
            <Connect in="100" to="1" out="100"/>
            <Connect in="101" to="4" out="100"/>
            <Connect in="102" constant="-8"/>
            <Connect in="103" constant="-9"/>
            <Connect in="104" constant="-10"/>
        </Operator>
        <Operator id="4" type="A2AAB92C">
            <Connect in="100" constant="-11"/>
            <Connect in="101" input="3"/>
        </Operator>
        <Operator id="5" type="D729EF5D">
            <Connect in="100" to="3" out="101"/>
            <Connect in="101" to="6" out="100"/>
            <Connect in="102" constant="-12"/>
            <Connect in="103" constant="-13"/>
            <Connect in="104" constant="-14"/>
        </Operator>
        <Operator id="6" type="A2AAB92C">
            <Connect in="100" constant="-15"/>
            <Connect in="101" input="4"/>
        </Operator>
        <Operator id="7" type="D729EF5D">
            <Connect in="100" to="5" out="100"/>
            <Connect in="101" to="8" out="100"/>
            <Connect in="102" constant="-16"/>
            <Connect in="103" constant="-17"/>
            <Connect in="104" constant="-18"/>
        </Operator>
        <Operator id="8" type="A2AAB92C">
            <Connect in="100" constant="-19"/>
            <Connect in="101" input="5"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="Frame" name="Out" description="" to="7" out="101"/>
    </Outputs>
</Procedure>
