<?xml version="1.0"?>
<Procedure Version="5" type="2A8302F3">
    <Inputs>
        <Input id="1" type="List" name="Assets" description="List of assets"/>
        <Input id="2" type="Integer" name="#" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-6" type="Integer">1</Constant>
        <Constant id="-12" type="Integer">1</Constant>
        <Constant id="-14" type="Integer">0</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="5C4E98DC">
            <Connect in="100" input="1"/>
        </Operator>
        <Operator id="2" type="AC2F6398">
            <Connect in="100" input="2"/>
            <Connect in="101" constant="-3"/>
            <Connect in="102" to="3" out="100"/>
        </Operator>
        <Operator id="3" type="A2D1BB58">
            <Connect in="100" to="1" out="100"/>
            <Connect in="101" constant="-6"/>
        </Operator>
        <Operator id="4" type="D56CEA6D">
            <Connect in="100" input="1"/>
            <Connect in="101" to="2" out="101"/>
        </Operator>
        <Operator id="6" type="B06BD8E5">
            <Connect in="100" to="4" out="100"/>
            <Connect in="101" constant="-12"/>
        </Operator>
        <Operator id="7" type="B33D6C3E">
            <Connect in="100" to="4" out="100"/>
            <Connect in="101" constant="-14"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="Integer" name="ID" description="" to="7" out="100"/>
        <Output id="2" type="Frame" name="Bounds" description="" to="6" out="100"/>
        <Output id="3" type="Integer" name="#" description="" to="2" out="100"/>
    </Outputs>
</Procedure>
