<?xml version="1.0"?>
<Procedure Version="5" type="197B2FBE">
    <Inputs>
        <Input id="1" type="Integer" name="Index" description=""/>
        <Input id="2" type="Integer" name="0" description=""/>
        <Input id="3" type="Integer" name="1" description=""/>
        <Input id="4" type="Integer" name="2" description=""/>
        <Input id="5" type="Integer" name="3" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-5" type="Integer">0</Constant>
        <Constant id="-10" type="Integer">1</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="C0D4BFBD">
            <Connect in="100" to="2" out="100"/>
            <Connect in="101" input="2"/>
            <Connect in="102" input="3"/>
        </Operator>
        <Operator id="2" type="60628950">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-5"/>
        </Operator>
        <Operator id="3" type="C0D4BFBD">
            <Connect in="100" to="2" out="100"/>
            <Connect in="101" input="4"/>
            <Connect in="102" input="5"/>
        </Operator>
        <Operator id="4" type="C0D4BFBD">
            <Connect in="100" to="5" out="100"/>
            <Connect in="101" to="1" out="100"/>
            <Connect in="102" to="3" out="100"/>
        </Operator>
        <Operator id="5" type="60628950">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-10"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="Integer" name="Out" description="" to="4" out="100"/>
    </Outputs>
</Procedure>
