<?xml version="1.0"?>
<Procedure Version="5" type="D5804B5C">
    <Inputs>
        <Input id="1" type="Float" name="Value" description=""/>
        <Input id="2" type="Float" name="Step" description=""/>
    </Inputs>
    <Constants/>
    <Operators>
        <Operator id="1" type="DED78D0E">
            <Connect in="100" input="1"/>
            <Connect in="101" input="2"/>
        </Operator>
        <Operator id="2" type="D02B1A81">
            <Connect in="100" to="1" out="100"/>
        </Operator>
        <Operator id="3" type="971515D0">
            <Connect in="100" to="2" out="100"/>
            <Connect in="101" input="2"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="Float" name="" description="" to="3" out="100"/>
    </Outputs>
</Procedure>
