<?xml version="1.0"?>
<Procedure Version="5" type="7B7DB88B">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-2" type="Float">0.500000</Constant>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-4" type="Integer">0</Constant>
        <Constant id="-5" type="Bool">True</Constant>
        <Constant id="-11" type="ModelSegment"></Constant>
        <Constant id="-12" type="ModelSegment"></Constant>
        <Constant id="-13" type="Float">0.500000</Constant>
        <Constant id="-14" type="Integer">0</Constant>
        <Constant id="-15" type="Integer">1</Constant>
        <Constant id="-16" type="Bool">True</Constant>
        <Constant id="-30" type="Integer">1</Constant>
        <Constant id="-31" type="Integer">2</Constant>
        <Constant id="-35" type="Integer">-1</Constant>
        <Constant id="-36" type="Integer">2</Constant>
        <Constant id="-38" type="Integer">-2</Constant>
        <Constant id="-39" type="Integer">2</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="E853B53E">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-2"/>
            <Connect in="102" constant="-3"/>
            <Connect in="103" constant="-4"/>
            <Connect in="104" constant="-5"/>
        </Operator>
        <Operator id="3" type="3A07A702">
            <Connect in="100" to="8" out="1"/>
            <Connect in="101" to="9" out="1"/>
            <Connect in="102" to="10" out="1"/>
            <Connect in="103" to="11" out="1"/>
            <Connect in="104" constant="-11"/>
            <Connect in="105" constant="-12"/>
        </Operator>
        <Operator id="5" type="E853B53E">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-13"/>
            <Connect in="102" constant="-14"/>
            <Connect in="103" constant="-15"/>
            <Connect in="104" constant="-16"/>
        </Operator>
        <Operator id="8" type="7B086D40">
            <Connect in="1" to="13" out="100"/>
        </Operator>
        <Operator id="9" type="7B086D40">
            <Connect in="1" to="14" out="100"/>
        </Operator>
        <Operator id="10" type="7B086D40">
            <Connect in="1" to="15" out="100"/>
        </Operator>
        <Operator id="11" type="7B086D40">
            <Connect in="1" to="5" out="102"/>
        </Operator>
        <Operator id="13" type="EBC5C37C">
            <Connect in="100" to="1" out="100"/>
            <Connect in="101" constant="-30"/>
            <Connect in="102" constant="-31"/>
        </Operator>
        <Operator id="14" type="EBC5C37C">
            <Connect in="100" to="1" out="102"/>
            <Connect in="101" constant="-35"/>
            <Connect in="102" constant="-36"/>
        </Operator>
        <Operator id="15" type="EBC5C37C">
            <Connect in="100" to="5" out="100"/>
            <Connect in="101" constant="-38"/>
            <Connect in="102" constant="-39"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="3" out="100"/>
    </Outputs>
</Procedure>
