<?xml version="1.0"?>
<Procedure Version="5" type="7B0FA74B">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
        <Input id="2" type="Integer" name="Select" description=""/>
        <Input id="3" type="Float" name="Object Size" description=""/>
        <Input id="4" type="Float" name="Spacer Size" description=""/>
        <Input id="5" type="Integer" name="Start Index" description=""/>
        <Input id="6" type="Integer" name="Total Objects" description=""/>
        <Input id="7" type="Integer" name="Wall Seed" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-6" type="Float">1.000000</Constant>
        <Constant id="-7" type="Float">1.000000</Constant>
        <Constant id="-13" type="ModelSegment"></Constant>
        <Constant id="-16" type="ModelSegment"></Constant>
        <Constant id="-27" type="ModelSegment"></Constant>
        <Constant id="-28" type="ModelSegment"></Constant>
        <Constant id="-32" type="Integer">2</Constant>
        <Constant id="-37" type="ModelSegment"></Constant>
        <Constant id="-44" type="Integer">1</Constant>
        <Constant id="-53" type="Integer">0</Constant>
        <Constant id="-54" type="Integer">0</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="D1CF1CFF">
            <Connect in="1" input="1"/>
            <Connect in="2" input="2"/>
            <Connect in="3" constant="-3"/>
            <Connect in="4" input="3"/>
            <Connect in="5" input="4"/>
            <Connect in="6" constant="-6"/>
            <Connect in="7" constant="-7"/>
            <Connect in="8" input="5"/>
            <Connect in="9" input="6"/>
        </Operator>
        <Operator id="2" type="0F68AB71">
            <Connect in="1" to="1" out="1"/>
            <Connect in="2" to="3" out="1"/>
            <Connect in="3" to="4" out="1"/>
            <Connect in="4" constant="-13"/>
            <Connect in="5" constant="-37"/>
            <Connect in="6" to="7" out="1"/>
            <Connect in="7" constant="-16"/>
        </Operator>
        <Operator id="3" type="7B0FA74B">
            <Connect in="1" to="1" out="2"/>
            <Connect in="2" to="1" out="3"/>
            <Connect in="3" input="3"/>
            <Connect in="4" input="4"/>
            <Connect in="5" to="1" out="11"/>
            <Connect in="6" to="1" out="13"/>
            <Connect in="7" constant="-53"/>
        </Operator>
        <Operator id="4" type="7B0FA74B">
            <Connect in="1" to="1" out="4"/>
            <Connect in="2" to="1" out="5"/>
            <Connect in="3" input="3"/>
            <Connect in="4" input="4"/>
            <Connect in="5" to="1" out="12"/>
            <Connect in="6" to="1" out="13"/>
            <Connect in="7" constant="-54"/>
        </Operator>
        <Operator id="7" type="DBAD4334">
            <Connect in="1" to="1" out="8"/>
        </Operator>
        <Operator id="8" type="C01FB46B">
            <Connect in="100" to="9" out="100"/>
            <Connect in="101" constant="-27"/>
            <Connect in="102" constant="-28"/>
        </Operator>
        <Operator id="9" type="BB6EAC9D">
            <Connect in="100" to="1" out="14"/>
            <Connect in="101" to="10" out="100"/>
        </Operator>
        <Operator id="10" type="C71AF18D">
            <Connect in="100" to="1" out="13"/>
            <Connect in="101" constant="-32"/>
        </Operator>
        <Operator id="13" type="B596EA66">
            <Connect in="100" to="1" out="14"/>
            <Connect in="101" to="10" out="100"/>
        </Operator>
        <Operator id="14" type="A2D1BB58">
            <Connect in="100" to="15" out="100"/>
            <Connect in="101" to="1" out="14"/>
        </Operator>
        <Operator id="15" type="A2D1BB58">
            <Connect in="100" to="1" out="13"/>
            <Connect in="101" constant="-44"/>
        </Operator>
        <Operator id="17" type="C0D4BFBD">
            <Connect in="100" to="13" out="100"/>
            <Connect in="101" to="1" out="14"/>
            <Connect in="102" to="14" out="100"/>
        </Operator>
        <Operator id="18" type="0B64055F">
            <Connect in="100" input="7"/>
            <Connect in="101" to="17" out="100"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="Out" description="" to="2" out="1"/>
    </Outputs>
</Procedure>
