<?xml version="1.0"?>
<Procedure Version="5" type="DBAD4334">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants/>
    <Operators>
        <Operator id="1" type="C22F65F7">
            <Connect in="1" input="1"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="1" out="1"/>
    </Outputs>
</Procedure>
