<?xml version="1.0"?>
<Procedure Version="5" type="DA48E306">
    <Inputs/>
    <Constants>
        <Constant id="-1" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-2" type="Integer">24</Constant>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-4" type="Float">1.000000</Constant>
        <Constant id="-5" type="Float">1.000000</Constant>
        <Constant id="-6" type="Float">1.000000</Constant>
        <Constant id="-7" type="Float">1.000000</Constant>
        <Constant id="-8" type="Integer">0</Constant>
        <Constant id="-9" type="Integer">0</Constant>
        <Constant id="-15" type="Integer">0</Constant>
        <Constant id="-16" type="ModelSegment"></Constant>
        <Constant id="-17" type="ModelSegment"></Constant>
        <Constant id="-18" type="ModelSegment"></Constant>
        <Constant id="-19" type="ModelSegment"></Constant>
        <Constant id="-20" type="ModelSegment"></Constant>
        <Constant id="-21" type="ModelSegment"></Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="D1CF1CFF">
            <Connect in="1" constant="-1"/>
            <Connect in="2" constant="-2"/>
            <Connect in="3" constant="-3"/>
            <Connect in="4" constant="-4"/>
            <Connect in="5" constant="-5"/>
            <Connect in="6" constant="-6"/>
            <Connect in="7" constant="-7"/>
            <Connect in="8" constant="-8"/>
            <Connect in="9" constant="-9"/>
        </Operator>
        <Operator id="3" type="0F68AB71">
            <Connect in="1" constant="-15"/>
            <Connect in="2" constant="-16"/>
            <Connect in="3" constant="-17"/>
            <Connect in="4" constant="-18"/>
            <Connect in="5" constant="-19"/>
            <Connect in="6" constant="-20"/>
            <Connect in="7" constant="-21"/>
        </Operator>
    </Operators>
    <Outputs/>
</Procedure>
