<?xml version="1.0"?>
<Procedure Version="5" type="2571CD33">
    <Inputs>
        <Input id="1" type="Frame" name="Where?" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-1" type="String">House.Roof2x2</Constant>
        <Constant id="-2" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-13" type="Float">0.000000</Constant>
        <Constant id="-14" type="List"></Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="36BD1471">
            <Connect in="100" constant="-1"/>
            <Connect in="101" constant="-2"/>
            <Connect in="102" constant="-3"/>
        </Operator>
        <Operator id="3" type="A58A93E3">
            <Connect in="100" to="1" out="100"/>
            <Connect in="101" input="1"/>
            <Connect in="102" constant="-13"/>
            <Connect in="103" constant="-14"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="Object" description="" to="3" out="100"/>
    </Outputs>
</Procedure>
