<?xml version="1.0"?>
<Procedure Version="5" type="6F11A178">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-3" type="FColour">[0.000000,0.000000,0.000000,1.000000]</Constant>
        <Constant id="-4" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-7" type="Bool">False</Constant>
        <Constant id="-8" type="Bool">False</Constant>
        <Constant id="-9" type="Bool">False</Constant>
        <Constant id="-10" type="Bool">False</Constant>
        <Constant id="-11" type="Bool">False</Constant>
        <Constant id="-12" type="Float">2.000000</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="C22F65F7">
            <Connect in="1" input="1"/>
        </Operator>
        <Operator id="2" type="8CC08944">
            <Connect in="1" constant="-4"/>
            <Connect in="2" constant="-3"/>
        </Operator>
        <Operator id="3" type="6F171489">
            <Connect in="1" to="4" out="1"/>
            <Connect in="2" input="1"/>
            <Connect in="3" constant="-12"/>
        </Operator>
        <Operator id="4" type="0662B77B">
            <Connect in="1" constant="-7"/>
            <Connect in="2" constant="-8"/>
            <Connect in="3" constant="-9"/>
            <Connect in="4" constant="-10"/>
            <Connect in="5" constant="-11"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="3" out="1"/>
    </Outputs>
</Procedure>
