<?xml version="1.0"?>
<Procedure Version="5" type="28461C02">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-2" type="Float">2.000000</Constant>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-4" type="Integer">0</Constant>
        <Constant id="-5" type="Bool">True</Constant>
        <Constant id="-34" type="Integer">1</Constant>
        <Constant id="-35" type="Integer">2</Constant>
        <Constant id="-39" type="Integer">-1</Constant>
        <Constant id="-40" type="Integer">2</Constant>
        <Constant id="-41" type="Integer">-1</Constant>
        <Constant id="-42" type="Integer">2</Constant>
        <Constant id="-44" type="Float">2.000000</Constant>
        <Constant id="-45" type="Integer">0</Constant>
        <Constant id="-46" type="Integer">1</Constant>
        <Constant id="-47" type="Bool">True</Constant>
        <Constant id="-51" type="Float">2.000000</Constant>
        <Constant id="-52" type="Integer">0</Constant>
        <Constant id="-53" type="Integer">1</Constant>
        <Constant id="-54" type="Bool">True</Constant>
        <Constant id="-56" type="Float">2.000000</Constant>
        <Constant id="-57" type="Integer">0</Constant>
        <Constant id="-58" type="Integer">1</Constant>
        <Constant id="-59" type="Bool">True</Constant>
        <Constant id="-97" type="ModelSegment"></Constant>
        <Constant id="-107" type="Integer">0</Constant>
        <Constant id="-108" type="Integer">0</Constant>
        <Constant id="-110" type="Integer">-2</Constant>
        <Constant id="-111" type="Integer">2</Constant>
        <Constant id="-115" type="Integer">0</Constant>
        <Constant id="-116" type="Integer">2</Constant>
        <Constant id="-118" type="ModelSegment"></Constant>
        <Constant id="-120" type="Integer">1</Constant>
        <Constant id="-121" type="Integer">2</Constant>
        <Constant id="-123" type="Integer">-2</Constant>
        <Constant id="-124" type="Integer">2</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="E853B53E">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-2"/>
            <Connect in="102" constant="-3"/>
            <Connect in="103" constant="-4"/>
            <Connect in="104" constant="-5"/>
        </Operator>
        <Operator id="8" type="6F11A178">
            <Connect in="1" to="13" out="100"/>
        </Operator>
        <Operator id="12" type="EBC5C37C">
            <Connect in="100" to="15" out="101"/>
            <Connect in="101" constant="-34"/>
            <Connect in="102" constant="-35"/>
        </Operator>
        <Operator id="13" type="EBC5C37C">
            <Connect in="100" to="16" out="101"/>
            <Connect in="101" constant="-39"/>
            <Connect in="102" constant="-40"/>
        </Operator>
        <Operator id="14" type="EBC5C37C">
            <Connect in="100" to="16" out="102"/>
            <Connect in="101" constant="-41"/>
            <Connect in="102" constant="-42"/>
        </Operator>
        <Operator id="15" type="E853B53E">
            <Connect in="100" to="1" out="100"/>
            <Connect in="101" constant="-44"/>
            <Connect in="102" constant="-45"/>
            <Connect in="103" constant="-46"/>
            <Connect in="104" constant="-47"/>
        </Operator>
        <Operator id="16" type="E853B53E">
            <Connect in="100" to="1" out="102"/>
            <Connect in="101" constant="-51"/>
            <Connect in="102" constant="-52"/>
            <Connect in="103" constant="-53"/>
            <Connect in="104" constant="-54"/>
        </Operator>
        <Operator id="17" type="E853B53E">
            <Connect in="100" to="1" out="101"/>
            <Connect in="101" constant="-56"/>
            <Connect in="102" constant="-57"/>
            <Connect in="103" constant="-58"/>
            <Connect in="104" constant="-59"/>
        </Operator>
        <Operator id="22" type="1144B523">
            <Connect in="100" to="38" out="2"/>
            <Connect in="101" to="23" out="1"/>
            <Connect in="102" to="35" out="2"/>
            <Connect in="103" to="27" out="1"/>
            <Connect in="104" constant="-118"/>
            <Connect in="105" to="28" out="1"/>
            <Connect in="106" to="39" out="2"/>
            <Connect in="107" to="8" out="1"/>
            <Connect in="108" to="40" out="2"/>
            <Connect in="109" constant="-97"/>
        </Operator>
        <Operator id="23" type="6F11A178">
            <Connect in="1" to="12" out="100"/>
        </Operator>
        <Operator id="27" type="6F11A178">
            <Connect in="1" to="30" out="100"/>
        </Operator>
        <Operator id="28" type="6F11A178">
            <Connect in="1" to="29" out="100"/>
        </Operator>
        <Operator id="29" type="EBC5C37C">
            <Connect in="100" to="17" out="102"/>
            <Connect in="101" constant="-107"/>
            <Connect in="102" constant="-108"/>
        </Operator>
        <Operator id="30" type="EBC5C37C">
            <Connect in="100" to="17" out="100"/>
            <Connect in="101" constant="-110"/>
            <Connect in="102" constant="-111"/>
        </Operator>
        <Operator id="31" type="EBC5C37C">
            <Connect in="100" to="15" out="102"/>
            <Connect in="101" constant="-115"/>
            <Connect in="102" constant="-116"/>
        </Operator>
        <Operator id="35" type="347B51DF">
            <Connect in="1" to="31" out="100"/>
        </Operator>
        <Operator id="36" type="EBC5C37C">
            <Connect in="100" to="15" out="100"/>
            <Connect in="101" constant="-120"/>
            <Connect in="102" constant="-121"/>
        </Operator>
        <Operator id="37" type="EBC5C37C">
            <Connect in="100" to="16" out="100"/>
            <Connect in="101" constant="-123"/>
            <Connect in="102" constant="-124"/>
        </Operator>
        <Operator id="38" type="347B51DF">
            <Connect in="1" to="36" out="100"/>
        </Operator>
        <Operator id="39" type="347B51DF">
            <Connect in="1" to="37" out="100"/>
        </Operator>
        <Operator id="40" type="347B51DF">
            <Connect in="1" to="14" out="100"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="22" out="100"/>
    </Outputs>
</Procedure>
