<?xml version="1.0"?>
<Procedure Version="5" type="347B51DF">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-1" type="Float">0.000000</Constant>
        <Constant id="-2" type="List"></Constant>
        <Constant id="-4" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-5" type="Integer">0</Constant>
        <Constant id="-12" type="String"></Constant>
        <Constant id="-13" type="String">Roof_corner</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="A58A93E3">
            <Connect in="100" to="2" out="100"/>
            <Connect in="101" input="1"/>
            <Connect in="102" constant="-1"/>
            <Connect in="103" constant="-2"/>
        </Operator>
        <Operator id="2" type="36BD1471">
            <Connect in="100" constant="-13"/>
            <Connect in="101" constant="-4"/>
            <Connect in="102" constant="-5"/>
        </Operator>
        <Operator id="4" type="C22F65F7">
            <Connect in="1" input="1"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="2" type="ModelSegment" name="" description="" to="4" out="1"/>
    </Outputs>
</Procedure>
