<?xml version="1.0"?>
<Procedure Version="5" type="6CE81E66">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-2" type="String">House.Roof2x2</Constant>
        <Constant id="-3" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-4" type="Integer">0</Constant>
        <Constant id="-14" type="Float">0.000000</Constant>
        <Constant id="-15" type="List"></Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="C22F65F7">
            <Connect in="1" input="1"/>
        </Operator>
        <Operator id="2" type="36BD1471">
            <Connect in="100" constant="-2"/>
            <Connect in="101" constant="-3"/>
            <Connect in="102" constant="-4"/>
        </Operator>
        <Operator id="4" type="A58A93E3">
            <Connect in="100" to="2" out="100"/>
            <Connect in="101" input="1"/>
            <Connect in="102" constant="-14"/>
            <Connect in="103" constant="-15"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="4" out="100"/>
    </Outputs>
</Procedure>
