<?xml version="1.0"?>
<Procedure Version="5" type="DA5EB57E">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
        <Input id="2" type="Float" name="PillarSize" description="|Min=0|Max=2"/>
        <Input id="3" type="Float" name="RoofTaper" description="|Min=0|Max=2"/>
        <Input id="5" type="Bool" name="ExtraTier" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-2" type="Float">1.000000</Constant>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-4" type="Integer">2</Constant>
        <Constant id="-5" type="Bool">False</Constant>
        <Constant id="-7" type="Float">1.798701</Constant>
        <Constant id="-8" type="Integer">0</Constant>
        <Constant id="-9" type="Integer">2</Constant>
        <Constant id="-10" type="Bool">True</Constant>
        <Constant id="-12" type="FColour">[0.000000,0.070588,0.000000,1.000000]</Constant>
        <Constant id="-13" type="FColour">[0.600000,0.000000,0.000000,1.000000]</Constant>
        <Constant id="-17" type="ModelSegment"></Constant>
        <Constant id="-19" type="ModelSegment"></Constant>
        <Constant id="-29" type="Float">1.000000</Constant>
        <Constant id="-35" type="Integer">0</Constant>
        <Constant id="-38" type="Float">5.000000</Constant>
        <Constant id="-39" type="Integer">0</Constant>
        <Constant id="-40" type="Integer">2</Constant>
        <Constant id="-42" type="Float">0.000000</Constant>
        <Constant id="-43" type="Float">0.000000</Constant>
        <Constant id="-45" type="ModelSegment"></Constant>
        <Constant id="-47" type="Bool">False</Constant>
        <Constant id="-50" type="Integer">1</Constant>
        <Constant id="-51" type="Integer">1</Constant>
        <Constant id="-52" type="Integer">1</Constant>
        <Constant id="-53" type="Integer">1</Constant>
        <Constant id="-54" type="Integer">1</Constant>
        <Constant id="-55" type="Integer">1</Constant>
        <Constant id="-62" type="Float">0.000000</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="D729EF5D">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-2"/>
            <Connect in="102" constant="-3"/>
            <Connect in="103" constant="-4"/>
            <Connect in="104" constant="-5"/>
        </Operator>
        <Operator id="2" type="D729EF5D">
            <Connect in="100" to="1" out="101"/>
            <Connect in="101" constant="-7"/>
            <Connect in="102" constant="-8"/>
            <Connect in="103" constant="-9"/>
            <Connect in="104" constant="-10"/>
        </Operator>
        <Operator id="3" type="8CC08944">
            <Connect in="1" to="1" out="100"/>
            <Connect in="2" constant="-12"/>
        </Operator>
        <Operator id="4" type="8CC08944">
            <Connect in="1" to="2" out="101"/>
            <Connect in="2" constant="-13"/>
        </Operator>
        <Operator id="5" type="3A07A702">
            <Connect in="100" to="9" out="100"/>
            <Connect in="101" to="7" out="1"/>
            <Connect in="102" to="3" out="1"/>
            <Connect in="103" constant="-17"/>
            <Connect in="104" to="12" out="100"/>
            <Connect in="105" constant="-19"/>
        </Operator>
        <Operator id="7" type="DA486B65">
            <Connect in="1" to="8" out="1"/>
            <Connect in="2" input="2"/>
        </Operator>
        <Operator id="8" type="DA4C68BC">
            <Connect in="1" to="2" out="100"/>
            <Connect in="2" constant="-29"/>
        </Operator>
        <Operator id="9" type="87E75C7F">
            <Connect in="100" to="4" out="1"/>
            <Connect in="101" to="2" out="101"/>
            <Connect in="102" input="3"/>
            <Connect in="103" input="3"/>
            <Connect in="104" constant="-35"/>
        </Operator>
        <Operator id="10" type="E82F5975">
            <Connect in="100" to="13" out="100"/>
            <Connect in="101" constant="-38"/>
            <Connect in="102" constant="-39"/>
            <Connect in="103" constant="-40"/>
        </Operator>
        <Operator id="11" type="DA5EB57E">
            <Connect in="1" to="10" out="101"/>
            <Connect in="2" constant="-42"/>
            <Connect in="3" constant="-43"/>
            <Connect in="5" constant="-47"/>
        </Operator>
        <Operator id="12" type="C01FB46B">
            <Connect in="100" input="5"/>
            <Connect in="101" constant="-45"/>
            <Connect in="102" to="11" out="1"/>
        </Operator>
        <Operator id="13" type="E99E1179">
            <Connect in="100" input="1"/>
            <Connect in="101" to="14" out="100"/>
            <Connect in="102" constant="-50"/>
            <Connect in="103" constant="-51"/>
            <Connect in="104" constant="-52"/>
            <Connect in="105" constant="-53"/>
            <Connect in="106" constant="-54"/>
            <Connect in="107" constant="-55"/>
        </Operator>
        <Operator id="14" type="D2698D20">
            <Connect in="100" input="2"/>
            <Connect in="101" input="2"/>
            <Connect in="102" constant="-62"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="5" out="100"/>
    </Outputs>
</Procedure>
