<?xml version="1.0"?>
<Procedure Version="5" type="28461C02">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-2" type="Float">2.000000</Constant>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-4" type="Integer">0</Constant>
        <Constant id="-5" type="Bool">True</Constant>
        <Constant id="-8" type="Float">2.000000</Constant>
        <Constant id="-9" type="Integer">0</Constant>
        <Constant id="-10" type="Integer">1</Constant>
        <Constant id="-11" type="Bool">True</Constant>
        <Constant id="-34" type="Integer">1</Constant>
        <Constant id="-35" type="Integer">2</Constant>
        <Constant id="-39" type="Integer">-1</Constant>
        <Constant id="-40" type="Integer">2</Constant>
        <Constant id="-41" type="Integer">-2</Constant>
        <Constant id="-42" type="Integer">2</Constant>
        <Constant id="-44" type="Float">2.000000</Constant>
        <Constant id="-45" type="Integer">0</Constant>
        <Constant id="-46" type="Integer">1</Constant>
        <Constant id="-47" type="Bool">True</Constant>
        <Constant id="-51" type="Float">2.000000</Constant>
        <Constant id="-52" type="Integer">0</Constant>
        <Constant id="-53" type="Integer">1</Constant>
        <Constant id="-54" type="Bool">True</Constant>
        <Constant id="-56" type="Float">2.000000</Constant>
        <Constant id="-57" type="Integer">0</Constant>
        <Constant id="-58" type="Integer">1</Constant>
        <Constant id="-59" type="Bool">True</Constant>
        <Constant id="-79" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-80" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-81" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-82" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-83" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-84" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-85" type="Frame">[0,0,0][1,0,0][0,1,0][0,0,1][1,1,1]</Constant>
        <Constant id="-90" type="ModelSegment"></Constant>
        <Constant id="-91" type="ModelSegment"></Constant>
        <Constant id="-92" type="ModelSegment"></Constant>
        <Constant id="-93" type="ModelSegment"></Constant>
        <Constant id="-94" type="ModelSegment"></Constant>
        <Constant id="-95" type="ModelSegment"></Constant>
        <Constant id="-96" type="ModelSegment"></Constant>
        <Constant id="-97" type="ModelSegment"></Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="E853B53E">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-2"/>
            <Connect in="102" constant="-3"/>
            <Connect in="103" constant="-4"/>
            <Connect in="104" constant="-5"/>
        </Operator>
        <Operator id="3" type="E853B53E">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-8"/>
            <Connect in="102" constant="-9"/>
            <Connect in="103" constant="-10"/>
            <Connect in="104" constant="-11"/>
        </Operator>
        <Operator id="8" type="6F11A178">
            <Connect in="1" constant="-85"/>
        </Operator>
        <Operator id="9" type="6F11A178">
            <Connect in="1" constant="-84"/>
        </Operator>
        <Operator id="10" type="6F11A178">
            <Connect in="1" constant="-83"/>
        </Operator>
        <Operator id="11" type="6F11A178">
            <Connect in="1" constant="-82"/>
        </Operator>
        <Operator id="12" type="EBC5C37C">
            <Connect in="100" constant="-79"/>
            <Connect in="101" constant="-34"/>
            <Connect in="102" constant="-35"/>
        </Operator>
        <Operator id="13" type="EBC5C37C">
            <Connect in="100" constant="-80"/>
            <Connect in="101" constant="-39"/>
            <Connect in="102" constant="-40"/>
        </Operator>
        <Operator id="14" type="EBC5C37C">
            <Connect in="100" constant="-81"/>
            <Connect in="101" constant="-41"/>
            <Connect in="102" constant="-42"/>
        </Operator>
        <Operator id="15" type="E853B53E">
            <Connect in="100" to="1" out="100"/>
            <Connect in="101" constant="-44"/>
            <Connect in="102" constant="-45"/>
            <Connect in="103" constant="-46"/>
            <Connect in="104" constant="-47"/>
        </Operator>
        <Operator id="16" type="E853B53E">
            <Connect in="100" to="1" out="102"/>
            <Connect in="101" constant="-51"/>
            <Connect in="102" constant="-52"/>
            <Connect in="103" constant="-53"/>
            <Connect in="104" constant="-54"/>
        </Operator>
        <Operator id="17" type="E853B53E">
            <Connect in="100" to="1" out="101"/>
            <Connect in="101" constant="-56"/>
            <Connect in="102" constant="-57"/>
            <Connect in="103" constant="-58"/>
            <Connect in="104" constant="-59"/>
        </Operator>
        <Operator id="21" type="6F11A178">
            <Connect in="1" to="15" out="100"/>
        </Operator>
        <Operator id="22" type="1144B523">
            <Connect in="100" to="21" out="1"/>
            <Connect in="101" to="23" out="1"/>
            <Connect in="102" constant="-90"/>
            <Connect in="103" constant="-91"/>
            <Connect in="104" constant="-92"/>
            <Connect in="105" constant="-93"/>
            <Connect in="106" constant="-94"/>
            <Connect in="107" constant="-95"/>
            <Connect in="108" constant="-96"/>
            <Connect in="109" constant="-97"/>
        </Operator>
        <Operator id="23" type="6F11A178">
            <Connect in="1" to="15" out="102"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="22" out="100"/>
    </Outputs>
</Procedure>
