<?xml version="1.0"?>
<Procedure Version="5" type="DA5EB57E">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
    </Inputs>
    <Constants>
        <Constant id="-2" type="Float">1.000000</Constant>
        <Constant id="-3" type="Integer">0</Constant>
        <Constant id="-4" type="Integer">2</Constant>
        <Constant id="-5" type="Bool">False</Constant>
        <Constant id="-7" type="Float">1.798701</Constant>
        <Constant id="-8" type="Integer">0</Constant>
        <Constant id="-9" type="Integer">2</Constant>
        <Constant id="-10" type="Bool">True</Constant>
        <Constant id="-12" type="FColour">[0.000000,0.070588,0.000000,1.000000]</Constant>
        <Constant id="-13" type="FColour">[0.600000,0.000000,0.000000,1.000000]</Constant>
        <Constant id="-17" type="ModelSegment"></Constant>
        <Constant id="-18" type="ModelSegment"></Constant>
        <Constant id="-19" type="ModelSegment"></Constant>
        <Constant id="-29" type="Float">1.000000</Constant>
        <Constant id="-33" type="Float">0.493506</Constant>
        <Constant id="-34" type="Float">0.467532</Constant>
        <Constant id="-35" type="Integer">0</Constant>
    </Constants>
    <Operators>
        <Operator id="1" type="D729EF5D">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-2"/>
            <Connect in="102" constant="-3"/>
            <Connect in="103" constant="-4"/>
            <Connect in="104" constant="-5"/>
        </Operator>
        <Operator id="2" type="D729EF5D">
            <Connect in="100" to="1" out="101"/>
            <Connect in="101" constant="-7"/>
            <Connect in="102" constant="-8"/>
            <Connect in="103" constant="-9"/>
            <Connect in="104" constant="-10"/>
        </Operator>
        <Operator id="3" type="8CC08944">
            <Connect in="1" to="1" out="100"/>
            <Connect in="2" constant="-12"/>
        </Operator>
        <Operator id="4" type="8CC08944">
            <Connect in="1" to="2" out="101"/>
            <Connect in="2" constant="-13"/>
        </Operator>
        <Operator id="5" type="3A07A702">
            <Connect in="100" to="9" out="100"/>
            <Connect in="101" to="7" out="1"/>
            <Connect in="102" to="3" out="1"/>
            <Connect in="103" constant="-17"/>
            <Connect in="104" constant="-18"/>
            <Connect in="105" constant="-19"/>
        </Operator>
        <Operator id="7" type="DA486B65">
            <Connect in="1" to="8" out="1"/>
        </Operator>
        <Operator id="8" type="DA4C68BC">
            <Connect in="1" to="2" out="100"/>
            <Connect in="2" constant="-29"/>
        </Operator>
        <Operator id="9" type="87E75C7F">
            <Connect in="100" to="4" out="1"/>
            <Connect in="101" to="2" out="101"/>
            <Connect in="102" constant="-33"/>
            <Connect in="103" constant="-34"/>
            <Connect in="104" constant="-35"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="5" out="100"/>
    </Outputs>
</Procedure>
